// <auto-generated />
using System;
using ControleFrotas.Models.Insfrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIControleFrotas.Migrations
{
    [DbContext(typeof(ControleFrotaContext))]
    [Migration("20220307125101_Ajustes")]
    partial class Ajustes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControleFrotas.Models.Domain.Entites.Motorista", b =>
                {
                    b.Property<string>("MotoristaId")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cnh")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("ValidadeCnh")
                        .HasColumnType("datetime");

                    b.HasKey("MotoristaId");

                    b.ToTable("Motoristas");
                });

            modelBuilder.Entity("ControleFrotas.Models.Domain.Entites.MotoristaVeiculo", b =>
                {
                    b.Property<string>("VeiculoId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MotoristaId")
                        .HasColumnType("varchar(50)");

                    b.HasKey("VeiculoId", "MotoristaId");

                    b.HasIndex("MotoristaId");

                    b.ToTable("MotoristasVeiculos");
                });

            modelBuilder.Entity("ControleFrotas.Models.Domain.Entites.Veiculo", b =>
                {
                    b.Property<string>("VeiculoId")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Placa")
                        .HasColumnType("varchar(20)");

                    b.HasKey("VeiculoId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("ControleFrotas.Models.Domain.Entites.MotoristaVeiculo", b =>
                {
                    b.HasOne("ControleFrotas.Models.Domain.Entites.Motorista", "Motorista")
                        .WithMany("Veiculos")
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFrotas.Models.Domain.Entites.Veiculo", "Veiculo")
                        .WithMany("Motoristas")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
